# 配置端口信息
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    context-path: /

# 数据库连接四大参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yishun
    url: jdbc:mysql://localhost:3306/zoo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 3050066014@qq.com
    #授权码
    password: zqkbkxwzyhupdhbi
    #端口
    port: 25
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  type-aliases-package: com.beordie.model.entity
  mapper-locations: "classpath:mappers/*.xml"

image:
  visitor: C:/Users/30500/Desktop/课程实习/zoos/zoos-serve/src/main/resources/static/image/
  upload: C:/Users/30500/Desktop/课程实习/zoos/zoos-serve/src/main/resources/static

