# 配置端口信息
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# 数据库连接四大参数
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yishun
    url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf-8
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

# mybatis 的简单配置
mybatis:
  type-aliases-package: com.beordie.model
  mapper-locations: "classpath:mappers/*.xml"

